name: Momentum
description: A high performance web framewrok in dart
  
version: 0.1.5

environment:
  sdk: '>=2.17.5 <3.0.0'
  
dependencies: { mime: ^1.0.2, mongo_dart: ^0.7.4+1, mysql1: ^0.20.0, mysql_client: ^0.0.24, path: ^1.8.2, sqlite3: ^1.7.2, watcher: ^1.0.1,}
  
  
