name: endeavor
description: A high performance web framework for the web wizards.
  
version: 0.1.6
homepage: https://github.com/x-i-f-r-a/Endeavor

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: '>=2.17.5 <3.0.0'
  
dependencies: { mime: ^1.0.2, mysql1: ^0.20.0,  path: ^1.8.2, sqlite3: ^1.7.2, watcher: ^1.0.1,}
  
  
